apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: tanzu-java-web-app
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
    tanzu.app.live.view.application.port: "8080"
    tanzu.app.live.view.application.actuator.port: "8080"
    # tanzu.app.live.view.application.flavours: spring-boot
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/aletor92/tanzu-java-web-app
      ref:
        branch: main 
  # serviceClaims:
  #   - name: rmq-1
  #     ref:
  #       apiVersion: v1beta1
  #       kind: RabbitmqCluster
  #       name: rmq-1